= This site was built with hubpress.io
:hp-tags: Technology

I needed a "quick", free and server-less blog with domain forwarding. I liked the http://jekyllrb.com/[Jekyll] static site generator, though there were too many caveats. The open source projet http://hubpress.io/[HubPress] seemed solid, fork a repo, change a config.json file and then good to go, right? Not so fast.

I ran into several problems, but mostly were my legacy problems. I had previously setup two blogs using https://pages.github.com/[GitHub Pages]. One of those projects had a `_config.yml` file that redirected to an old, unused and completely different domain. It also didn't help that I had several CNAME redirects setup in AWS Route 53. After deleting both old repos, removing A and CNAME records within AWS, we're good to go.

Here's the configuration I ended up with: `https://github.com/ryanlitalien/website/blob/609b3cee892e104aedea71aabde16cd85ea4b63b/hubpress/config.json`

I might open a pull request with the guys at HubPress to format the `config.json` with pretty print.

Not bad for the first post :)